apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: gcp-providers
  labels:
    entity: cluster
    capability: access
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec: {}
